# dependabot.yml - Enables dependabot

version: 2
updates:
  # Enable version updates for pip
  - package-ecosystem: "pip"
    directory: "Final Work Pratical/backend/"
    schedule:
      interval: "daily"

  # Manter dependências para npm
  - package-ecosystem: "npm"
    directory: "Final Work Pratical/frontend/"
    schedule:
      interval: "daily"
