# Generated by Django 3.1.5 on 2021-01-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.PositiveSmallIntegerField(choices=[(0, 'Strength'), (1, 'Weakness'), (2, 'Threat'), (4, 'Opportunity')], verbose_name='Factor classification')),
                ('description', models.CharField(max_length=50, verbose_name='Factor description')),
                ('importance', models.PositiveSmallIntegerField(choices=[(0, 'Unimportant'), (1, 'Of Little Importance'), (2, 'Moderately Important '), (3, 'Important'), (4, 'Very Important')], verbose_name='Factor importance')),
            ],
        ),
        migrations.CreateModel(
            name='Quadrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.PositiveSmallIntegerField(choices=[(1, 'Strengths'), (2, 'Weaknesses'), (3, 'Opportunities'), (4, 'Threats')], verbose_name='Quadrant type')),
            ],
        ),
        migrations.CreateModel(
            name='SWOTAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Analysis title')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Analysis short description')),
                ('starting_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('state', models.IntegerField(choices=[(1, 'In progress'), (2, 'Closed'), (3, 'Archived')], default=1)),
            ],
            options={
                'verbose_name': 'SWOT analysis',
                'verbose_name_plural': 'SWOT analyses',
            },
        ),
    ]
