# Generated by Django 3.1.5 on 2021-01-24 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swot_analysis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='swotanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quadrant',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quadrants', to='swot_analysis.swotanalysis'),
        ),
        migrations.AddField(
            model_name='factor',
            name='quadrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='swot_analysis.quadrant'),
        ),
        migrations.AlterUniqueTogether(
            name='swotanalysis',
            unique_together={('user', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='quadrant',
            unique_together={('name', 'analysis')},
        ),
    ]
