# Generated by Django 3.1.5 on 2021-01-22 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swot_analysis', '0002_swotanalysis_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='swotanalysis',
            options={'verbose_name': 'SWOT analysis', 'verbose_name_plural': 'SWOT analyses'},
        ),
    ]
