# Generated by Django 3.1.5 on 2021-01-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot_analysis', '0002_auto_20210125_2240'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='swotanalysis',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='swotanalysis',
            constraint=models.UniqueConstraint(fields=('user', 'title'), name='unique_analysis'),
        ),
    ]
