# Generated by Django 3.1.5 on 2021-01-24 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot_analysis', '0002_auto_20210124_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factor',
            name='factor_type',
        ),
        migrations.AlterUniqueTogether(
            name='quadrant',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='quadrant',
            constraint=models.UniqueConstraint(fields=('name', 'analysis'), name='unique_quadrant'),
        ),
    ]
