# Generated by Django 3.1.5 on 2021-01-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot_analysis', '0003_auto_20210125_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swotanalysis',
            name='state',
            field=models.IntegerField(choices=[(1, 'In progress'), (2, 'Closed')], default=1),
        ),
    ]
