# Generated by Django 3.1.5 on 2021-01-23 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('swot_analysis', '0003_auto_20210122_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swotanalysis',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Analysis short description'),
        ),
        migrations.AlterField(
            model_name='swotanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL),
        ),
    ]
