# Generated by Django 3.1.5 on 2021-01-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swot_analysis', '0004_auto_20210123_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_type', models.PositiveSmallIntegerField(choices=[(0, 'INTERNAL'), (1, 'EXTERNAL')], verbose_name='Factor type')),
                ('classification', models.PositiveSmallIntegerField(choices=[('INTERNAL', ((1, 'Strength'), (2, 'Weakness'))), ('EXTERNAL', ((4, 'Opportunity'), (5, 'Threat')))], verbose_name='Factor classification')),
                ('description', models.CharField(max_length=50, verbose_name='Factor description')),
                ('importance', models.IntegerField(choices=[(0, 'Unimportant'), (1, 'Of Little Importance'), (2, 'Moderately Important '), (3, 'Important'), (4, 'Very Important')], verbose_name='Factor importance')),
            ],
        ),
    ]
